services:
  - type: web
    name: jobportal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobportal.wsgi.application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: jobportal-db
          property: connectionString

databases:
  - name: jobportal-db
    plan: free
