# Generated by Django 6.0.5 on 2026-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('applied_date', models.DateField()),
                ('status', models.CharField(choices=[('review', 'In Review'), ('shortlisted', 'Shortlisted'), ('assessment', 'Assessment'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='review', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('salary', models.CharField(blank=True, max_length=80)),
                ('job_type', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='One responsibility per line')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('next_step', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
