# Generated by Django 6.0.5 on 2026-06-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
