# Generated by Django 6.0.5 on 2026-05-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('initials', models.CharField(max_length=8)),
                ('role', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('education', models.CharField(max_length=180)),
                ('projects', models.TextField(help_text='One project per line')),
                ('avatar_theme', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidateapp.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
