# Generated by Django 6.0.5 on 2026-05-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('initial', models.CharField(max_length=8)),
                ('industry', models.CharField(max_length=120)),
                ('open_jobs', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('benefits', models.TextField(help_text='One benefit per line')),
                ('logo_theme', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'employer companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('applicant_name', models.CharField(max_length=120)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employerapp.employercompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('job_type', models.CharField(default='Full time', max_length=80)),
                ('mode', models.CharField(default='Hybrid', max_length=80)),
                ('salary', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employerapp.employercompany')),
            ],
            options={
                'ordering': ['company__name', 'title'],
            },
        ),
    ]
