# Generated by Django 6.0.5 on 2026-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_reset_to_current_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employer',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
